# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ItaliaApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ItaliaApp

  pod 'React', :path => "../node_modules/react-native", :subspecs => [
    "Core",
    "ART",
    "RCTActionSheet",
    "RCTAnimation",
    "RCTCameraRoll",
    "RCTGeolocation",
    "RCTImage",
    "RCTNetwork",
    "RCTText",
    "RCTVibration",
    "RCTWebSocket",
    "DevSupport",
    "BatchedBridge"
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  target 'ItaliaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
